apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    env:
     - name: MONGO_URL
       value: mongodb.roboshop.internal
    
     - name: REDIS_URL
       value: redis.roboshop.internal

     - name: ENVIRONMENT
       value: dev