apiVersion: v1
kind: Pod
metadata:
  name: centos
spec:
  containers:
  - name: centos
    image: centos:7
    command: ["sleep", "15000"]
    envFrom:  
     - secretRef:
        name : amazcredentials
---

apiVersion: v1
kind: Secret
metadata:
  name: amazcredentials
data:
 username: c2Fua2FscAo=
 password: U2Fua2FscDEyMwo= 
