apiVersion: v1
kind: Namespace
metadata:
  name: roboshop
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  Namespace: roboshop
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-svc
  Namespace: roboshop
spec:
  selector:
    app: nginx
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80